version: '3.5'

services:

  backend:
    image: tennuem/task
    container_name: backend
    ports:
      - 8080:8080
      - 9153:9153
    environment:
      TASK_SERVER_HTTP_PORT: 8080
      TASK_LOGGER_LEVEL: "info"
      TASK_METRIC_PORT: 9153
    networks:
      - app-network

  frontend:
    image: tennuem/task-ui
    container_name: frontend
    ports:
      - 3000:80
    volumes:
      - web-root:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - frontend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email tennuem@gmail.com --agree-tos --no-eff-email --force-renewal -d tennuem.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/task/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge